<?php
/**
 * GoMage.com
 *
 * GoMage Feed Pro
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2020 GoMage.com (https://www.gomage.com)
 * @author       GoMage.com
 * @license      https://www.gomage.com/licensing  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 4.3.2
 * @since        Class available since Release 1.0
 */
?>
<?php
$feed = $this->getFeed();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Content Settings')?></h4>
        <div class="form-buttons">
            <button style="" onclick="window.open('https://wiki.gomage.com/hc/en-us/articles/115002729771-Content-Settings-for-CSV-TXT')" class="scalable go" type="button" id="feed_pro_help"><span><?php echo $this->__('Feed Pro Help')?></span></button>
        </div>
    </div>
    <div id="content_fieldset" class="fieldset ">
        <div>
            <p style="clear:both;padding-bottom:5px;overflow:hidden;">
                <label style="float:left;margin-right:20px; "><span style="float:left;margin-right:10px;"><?php echo $this->__('Show Header')?></span>
                    <select style="width:50px;" name="show_headers">
                        <option value="1" <?php if(intval($feed->getShowHeaders()) == 1 ):?> selected="selected" <?php endif;?>><?php echo $this->__('Yes');?></option>
                        <option value="0" <?php if(intval($feed->getShowHeaders()) == 0 ):?> selected="selected" <?php endif;?>><?php echo $this->__('No');?></option>
                    </select>
                </label>
                <label style="float:left;margin-right:20px; "><span style="float:left;margin-right:10px;"><?php echo $this->__('Delimiter')?></span>
                    <?php $delimiters = Mage::getModel('gomage_feed/adminhtml_system_config_source_csv_delimiter')->toOptionArray() ?>
                    <select style="width:100px;" name="delimiter">
                        <?php foreach ($delimiters as $delimiter): ?>
                            <option value="<?php echo $delimiter['value'] ?>" <?php if($feed->getDelimiter() == $delimiter['value']):?>selected="selected"<?php endif;?>><?php echo $delimiter['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </label>
                <label style="float:left; margin-right:20px;"><span style="float:left;margin-right:10px; "><?php echo $this->__('Enclosure')?></span>
                    <?php $enclosures = Mage::getModel('gomage_feed/adminhtml_system_config_source_csv_enclosure')->toOptionArray() ?>
                    <select style="width:190px;" name="enclosure">
                        <?php foreach ($enclosures as $enclosure): ?>
                            <option value="<?php echo $enclosure['value'] ?>" <?php if($feed->getEnclosure() == $enclosure['value']):?>selected="selected"<?php endif;?>><?php echo $enclosure['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </label>
            </p>
            <p style="clear:both">
                <label><span style="float:left; width: 170px;"><?php echo $this->__('Remove line break symbols')?></span>
                    <select style="width:50px;" name="remove_lb">
                        <option value="1" <?php if(intval($feed->getRemoveLb()) == 1 ):?> selected="selected" <?php endif;?>><?php echo $this->__('Yes');?></option>
                        <option value="0" <?php if(intval($feed->getRemoveLb()) == 0 ):?> selected="selected" <?php endif;?>><?php echo $this->__('No');?></option>
                    </select>
                </label><br/>
                <small><?php echo $this->__('This is the specific option that allows to remove line break symbols from a data feed.')?></small>
            </p>
            <p style="clear:both">
                <label><?php echo $this->__('Use Amazon Header')?></label>
                <select name="use_addition_header" onchange="gfp_changeAdditionHeader(this)">
                    <option value="1" <?php if(intval($feed->getUseAdditionHeader()) == 1 ):?> selected="selected" <?php endif;?>><?php echo $this->__('Yes');?></option>
                    <option value="0" <?php if(intval($feed->getUseAdditionHeader()) == 0 ):?> selected="selected" <?php endif;?>><?php echo $this->__('No');?></option>
                </select>
                <br/>
                <textarea id="addition_header" name="addition_header" style="width:470px;margin-top:5px;<?php if(intval($feed->getUseAdditionHeader()) == 0 ):?>display:none;<?php endif; ?>"><?php echo $feed->getData('addition_header'); ?></textarea>
            </p>
        </div>
    </div>
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Fields Mapping')?></h4>
        <div class="form-buttons">
            <?php if($feed->getId()>0):?>
                <button onclick="$('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'block'});return false;" class="button"><span><span><?php echo $this->__('Import Fields Settings');?></span></span></button>
                <button onclick="setLocation('<?php echo $this->getUrl('*/*/mappingexport', array('id'=>$feed->getId()))?>');return false;" class="button"><span><span><?php echo $this->__('Export Fields Settings');?></span></span></button>
                <button onclick="setLocation('<?php echo $this->getUrl('*/*/mappingexportftp', array('id'=>$feed->getId()))?>');return false;" class="button"><span><span><?php echo $this->__('Export Fields to Server');?></span></span></button>
            <?php else:?>
                <button onclick="showImportNotice();return false;" class="button disabled"><span><span><?php echo $this->__('Import Fields Settings');?></span></span></button>
                <button onclick="showExportNotice();return false;" class="button disabled"><span><span><?php echo $this->__('Export Fields Settings');?></span></span></button>
            <?php endif;?>
        </div>
    </div>
    <div id="mapping_fieldset" class="fieldset ">
        <div class="clear">
            <?php if($feed->getId()>0):?>
                <div class="gf-import left">
                    <p style="clear:both">
                        <label style="float: left; margin-right: 20px;">
                            <span style="float:left;margin-right: 10px;"><?php echo $this->__('System')?></span>
                            <select name="feed_system" id="feed_system" onchange="GomageFeedAdmin.setSystem(this.value)">
                            </select>
                        </label>
                        <label style="float: left; margin-right: 20px;">
                            <span style="float:left;margin-right: 10px;"><?php echo $this->__('Template')?></span>
                            <select name="feed_section" id="feed_section">
                            </select>
                        </label>
                        <button onclick="GomageFeedAdmin.submit(1, $('feed_section').value);return false;" class="button"><span><span><?php echo $this->__('Import');?></span></span></button>
                    </p>
                </div>
            <?php endif; ?>

            <?php if($feed->getId()>0):?>
                <div class="right">
                    <div id="<?php echo $this->getHtmlId() ?>" class="uploader">
                        <div class="buttons">
                            <?php if (Mage::helper('gomage_feed')->isModuleExists('Mage_Uploader')): ?>
                                <div id="<?php echo $this->getHtmlId() ?>-flash">
                                    <div id="<?php echo $this->getHtmlId() ?>-browse" style="display: inline-block;">
                                        <button id="<?php echo $this->getHtmlId() ?>-browse_button" title="Browse" type="button" class="scalable"><span><span><span>Browse</span></span></span></button>
                                    </div>
                                    <button id="<?php echo $this->getHtmlId() ?>-upload" title="Upload" type="button" class="scalable"><span><span><span>Upload</span></span></span></button>
                                    <div id="<?php echo $this->getHtmlId() ?>-container" class="file-row-info"></div>
                                </div>
                                <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
                                    <div id="{{id}}-container" class="file-row">
                                        <span class="file-info">{{name}} {{size}}</span>
                                        <span class="delete-button"><button  id="{{id}}" title="Remove" type="button" class="scalable delete" onclick="" style=""><span><span><span><?php echo $this->__('Remove') ?></span></span></span></button></span>
                                        <span class="progress-text"></span>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div id="<?php echo $this->getHtmlId() ?>-install-flash" style="display:none">
                                    <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
                                </div>
                                <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
                                    <div id="{{id}}" class="file-row">
                                        <span class="file-info">{{name}} ({{size}})</span>
                                        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
                                        <span class="progress-text"></span>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                                <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
                                    {{percent}}% {{uploaded}} / {{total}}
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            <?php else: ?>
                <p id="import-notice" style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;display:none;"><?php echo $this->__('After you save a new feed for the first time the "Import Fields Settings" button will be available')?></p>
                <p id="export-notice" style="clear:both;margin-bottom:7px;overflow:hidden;zoom:1;display:none;"><?php echo $this->__('After you save a new feed for the first time the "Export Fields Settings" button will be available')?></p>
            <?php endif; ?>
        </div>
        <?php
            echo $this->getLayout()->createBlock('gomage_feed/adminhtml_items_edit_tab_content_csv_rows')
                ->setTemplate('gomage/feed/item/edit/content/csv/rows.phtml')->toHtml();
        ?>
    </div>
</div>

<?php if($feed->getId()>0):?>
    <script type="text/javascript">
        //<![CDATA[

        <?php if (Mage::helper('gomage_feed')->isModuleExists('Mage_Uploader')): ?>
            <?php echo $this->getJsObjectName() ?> = new Uploader(<?php echo $this->getConfigJson() ?>);
            document.observe("uploader:success", function(event) {
                event.memo.files.each(function(file){
                    GomageFeedAdmin.submit(0, file.name);
                });
                $('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'none'});
            });
        <?php else: ?>
            var maxUploadFileSizeInBytes = <?php echo $this->getDataMaxSizeInBytes() ?>;
            var maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';
            <?php echo $this->getJsObjectName() ?> = new Flex.Uploader('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getUploaderUrl('media/uploader.swf') ?>', <?php echo $this->getConfigJson() ?>);
            <?php echo $this->getJsObjectName() ?>.onFilesComplete = function(completedFiles){
                completedFiles.each(function(file){
                    GomageFeedAdmin.submit(0, file.name);
                    <?php echo $this->getJsObjectName() ?>.removeFile(file.id);
                });
                $('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'none'});
            };
        <?php endif; ?>

        if ($('<?php echo $this->getHtmlId() ?>-flash') != undefined) {
            $('<?php echo $this->getHtmlId() ?>-flash').setStyle({display:'none'});
        }

        //]]>
    </script>
<?php endif; ?>