<?php
 /**
 * GoMage.com
 *
 * GoMage Feed Pro
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2020 GoMage.com (https://www.gomage.com)
 * @author       GoMage.com
 * @license      https://www.gomage.com/licensing  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 4.3.2
 * @since        Class available since Release 1.0
 */
?>
<?php
	$helper = Mage::helper('gomage_feed');
?>
<div id="gomage_feed_tabs_import_section_content">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $helper->__('Import Mapping');?></h4>
            <div class="form-buttons"></div>
        </div>
        <div id="main_fieldset" class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label">
                                <label for="mappingfile"><?php echo $helper->__('Mapping File');?><span class="required">*</span></label>
                            </td>
                            <td class="value" style="width:230px">
                                <input type="file" class="required-entry" title="<?php echo $helper->__('Mapping File');?>" value="" name="mappingfile" id="mappingfile">
                            </td>
                            <td  class="value">
                                <span id="continue_button"><button onclick="editForm.submit();return false;" class="scalable save" type="submit"><span><?php echo $helper->__('Import');?></span></button></span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>