<?php
/**
 * GoMage.com
 *
 * GoMage Feed Pro
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2018 GoMage.com (https://www.gomage.com)
 * @author       GoMage.com
 * @license      https://www.gomage.com/licensing  Single domain license
 * @terms of use https://www.gomage.com/terms-of-use
 * @version      Release: 4.1.0
 * @since        Class available since Release 1.0
 */
?>
<?php
$attribute = $this->getAttribute();
$_htmlName = 'option';
$_baseTypes = $this->getBaseTypes();
$_types = $this->getTypes();
$_operators = $this->getOperators();
$_attributes = $this->getProductAttributes();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Conditions and Values') ?></h4>
    </div>
    <div class="fieldset">
        <?php if ($attribute->getId()): ?>
            <div class="right">
                <button onclick="setLocation('<?php echo $this->getUrl('*/*/mappingImport', array('id' => $attribute->getId())) ?>');return false;"
                        class="button"><span><span><?php echo $this->__('Import Conditions'); ?></span></span>
                </button>
                <button onclick="setLocation('<?php echo $this->getUrl('*/*/mappingExport', array('id' => $attribute->getId())) ?>');return false;"
                        class="button"><span><span><?php echo $this->__('Export Conditions'); ?></span></span>
                </button>
            </div>
        <?php endif; ?>
        <div class="grid">
            <table class="data feed-dattr-table">
                <thead>
                    <tr class="headings">
                        <th class="col-condition"><?php echo $this->__('Condition') ?></th>
                        <th class="col-type"><?php echo $this->__('Type') ?></th>
                        <th class="col-value"><?php echo $this->__('Value') ?></th>
                        <th class="col-action"><?php echo $this->__('Action') ?></th>
                    </tr>
                </thead>
                <tbody id="rows-container"></tbody>
                <tfoot>
                    <tr>
                        <td class="col-actions-add" colspan="4">
                            <button type="button" id="add_new_row_button" class="button"><span><span><?php echo $this->__('Add New Value') ?></span></span></button>
                        </td>
                    </tr>
                    <tr class="headings">
                        <th colspan="4"><?php echo $this->__('Use Default') ?></th>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->__('Type') ?>
                        </td>
                        <td colspan="3">
                            <select class="select" name="default_type" id="default_type">
                                <?php foreach ($_baseTypes as $_type): ?>
                                    <option <?php if ($attribute->getData('default_type') == $_type['value']): ?>selected="selected"<?php endif; ?> value="<?php echo $_type['value'] ?>"><?php echo $_type['label'] ?></option>
                                <?php endforeach ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->__('Value') ?>
                        </td>
                        <td colspan="3">
                            <select class="select" name="default_value">
                                <option value=""><?php echo $this->__('Not Set') ?></option>
                                <?php foreach ($_attributes as $_attribute): ?>
                                    <option <?php if ($attribute->getData('default_value') == $_attribute['value']): ?>selected="selected"<?php endif; ?> value="<?php echo $_attribute['value'] ?>"><?php echo $_attribute['label'] ?></option>
                                <?php endforeach ?>
                            </select>
                            <input name="default_value" value="<?php echo $attribute->getData('default_value') ?>" class="input-text" type="text" />
                        </td>
                    </tr>

                </tfoot>
            </table>
        </div>
    </div>
</div>

<div class="template no-display" id="row-template">
    <table>
        <tbody>
            <tr class="option-row">
                <td class="col-condition">
                    <table>
                        <tbody id="conditions-container-{{row_id}}"></tbody>
                    </table>
                </td>
                <td class="col-type">
                    <select class="select type-select" data-row-id="{{row_id}}"
                            name="<?php echo $_htmlName ?>[{{row_id}}][value_type]">
                        <?php foreach ($_types as $_type): ?>
                            <option value="<?php echo $_type['value'] ?>"><?php echo $_type['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td class="col-value">
                    <table>
                        <tbody id="values-container-{{row_id}}"></tbody>
                    </table>
                </td>
                <td class="col-action">
                    <button title="<?php echo $this->__("Delete") ?>" type="button" class="button delete delete-row">
                        <span><?php echo $this->__("Delete") ?></span>
                    </button>
                    <button title="<?php echo $this->__("Add Condition") ?>" type="button"
                            class="button add add-condition" data-row-id="{{row_id}}">
                        <span><?php echo $this->__("Add Condition") ?></span>
                    </button>
                    <button title="<?php echo $this->__("Add Value") ?>" type="button" class="button add add-value"
                            data-row-id="{{row_id}}">
                        <span><?php echo $this->__("Add Value") ?></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="template no-display" id="condition-template">
    <table>
        <tbody>
            <tr>
                <td class="col-attribute">
                    <select class="select required-entry attribute-select"
                            name="<?php echo $_htmlName ?>[{{row_id}}][condition][{{condition_id}}][attribute_code]"
                            data-value="<?php echo $_htmlName ?>_{{row_id}}_condition_{{condition_id}}_value">
                        <option value=""><?php echo $this->__('Not Set') ?></option>
                        <?php foreach ($_attributes as $_attribute): ?>
                            <option value="<?php echo $_attribute['value'] ?>"><?php echo $_attribute['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td class="col-operator">
                    <select class="select operator-select" name="<?php echo $_htmlName ?>[{{row_id}}][condition][{{condition_id}}][condition]">
                        <?php foreach ($_operators as $_operator): ?>
                            <option value="<?php echo $_operator['value'] ?>"><?php echo $_operator['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td class="col-value">
                    <input name="<?php echo $_htmlName ?>[{{row_id}}][condition][{{condition_id}}][value]"
                           value="{{value}}" class="input-text" type="text"
                           id="<?php echo $_htmlName ?>_{{row_id}}_condition_{{condition_id}}_value_input"/>
                    <select class="select" disabled="disabled" style="display: none"
                            id="<?php echo $_htmlName ?>_{{row_id}}_condition_{{condition_id}}_value_select"
                            name="<?php echo $_htmlName ?>[{{row_id}}][condition][{{condition_id}}][value]">
                    </select>
                </td>
                <td class="col-action">
                    <button title="<?php echo $this->__("Delete") ?>" type="button" class="button delete delete-condition">
                        <span><?php echo $this->__("Delete") ?></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="template no-display" id="static-value-template">
    <table>
        <tbody>
            <tr>
                <td class="col-value">
                    <input name="<?php echo $_htmlName ?>[{{row_id}}][value]"
                           value="{{value}}" class="input-text" type="text"/>
                </td>
                <td>
                    <select class="select feed-ph">
                        <option><?php echo $this->__("Placeholder") ?></option>
                    </select>
                </td>
                <td class="col-action">
                    <button title="<?php echo $this->__("Delete") ?>" type="button" class="button delete feed-ph">
                        <span><?php echo $this->__("Delete") ?></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="template no-display" id="percent-value-template">
    <table>
        <tbody>
            <tr>
                <td class="col-value">
                    <input name="<?php echo $_htmlName ?>[{{row_id}}][value][percent]"
                           value="{{percent}}" class="input-text" type="text"/>
                </td>
                <td class="col-attribute">
                    <select class="select attribute-select" name="<?php echo $_htmlName ?>[{{row_id}}][value][code]">
                        <option value=""><?php echo $this->__('Not Set') ?></option>
                        <?php foreach ($_attributes as $_attribute): ?>
                            <option value="<?php echo $_attribute['value'] ?>"><?php echo $_attribute['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td class="col-action">
                    <button title="<?php echo $this->__("Delete") ?>" type="button" class="button delete feed-ph">
                        <span><?php echo $this->__("Delete") ?></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="template no-display" id="configurable-value-template">
    <table>
        <tbody>
            <tr>
                <td class="col-value">
                    <input name="<?php echo $_htmlName ?>[{{row_id}}][value][prefix]"
                           value="{{prefix}}" class="input-text" type="text"/>
                </td>
                <td class="col-attribute">
                    <select class="select attribute-select" name="<?php echo $_htmlName ?>[{{row_id}}][value][code]">
                        <option value=""><?php echo $this->__('Not Set') ?></option>
                        <?php foreach ($_attributes as $_attribute): ?>
                            <option value="<?php echo $_attribute['value'] ?>"><?php echo $_attribute['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td class="col-action">
                    <button title="<?php echo $this->__("Delete") ?>" type="button" class="button delete feed-ph">
                        <span><?php echo $this->__("Delete") ?></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="template no-display" id="attribute-value-template">
    <table>
        <tbody>
            <tr>
                <td class="col-value">
                    <input name="<?php echo $_htmlName ?>[{{row_id}}][value][{{value_id}}][prefix]"
                           value="{{prefix}}" class="input-text" type="text"/>
                </td>
                <td class="col-attribute">
                    <select class="select attribute-select"
                            name="<?php echo $_htmlName ?>[{{row_id}}][value][{{value_id}}][code]">
                        <option value=""><?php echo $this->__('Not Set') ?></option>
                        <?php foreach ($_attributes as $_attribute): ?>
                            <option value="<?php echo $_attribute['value'] ?>"><?php echo $_attribute['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </td>
                <td class="col-action">
                    <button title="<?php echo $this->__("Delete") ?>" type="button" class="button delete delete-value">
                        <span><?php echo $this->__("Delete") ?></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    document.observe("dom:loaded", function(){
        new GoMage.Rows({
            "rowsData": <?php echo $this->getRows(); ?>,
            "url": "<?php echo $this->getUrl('*/*/attributeValue') ?>"
        });
    });
</script>